disquaire_project/disquaire_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from store import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^store/', include('store.urls', namespace='store')),
    url(r'^content/', admin.site.urls)
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

disquaire_project/store/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.listing, name='listing'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^search/$', views.search, name='search'),
]

disquaire_project/store/models.py
# -*- coding: utf-8 -*- 
from django.db import models


class Artist(models.Model):
    name = models.CharField('Nom', max_length=200, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name ="artiste"


class Contact(models.Model):
    email = models.EmailField(max_length=100)
    name = models.CharField('Nom',max_length=200)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name ="contact"

class Album(models.Model):
    reference = models.IntegerField('référence', null=True)
    created_at = models.DateTimeField('date de création', auto_now_add=True)
    available = models.BooleanField('disponible', default=True)
    title = models.CharField('titre', max_length=200)
    picture = models.TextField("URL de l'image", )
    artists = models.ManyToManyField(Artist, related_name='albums', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name ="disque"


class Booking(models.Model):
    created_at = models.DateTimeField("date d'envoi", auto_now_add=True)
    contacted = models.BooleanField('demande traitée ?', default=False)
    album = models.OneToOneField(Album)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)

    def __str__(self):
        return self.contact.name

    class Meta:
        verbose_name ="réservation"

disquaire_project/store/forms.py
from django.forms import ModelForm, TextInput, EmailInput
from django.forms.utils import ErrorList

from .models import Contact


class ParagraphErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()
    def as_divs(self):
        if not self: return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<p class="small error">%s</p>' % e for e in self])

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email"]
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'})
        }

disquaire_project/store/views.py
# -*- coding: utf-8 -*- 

#Encoding gives “'ascii' codec can't encode character … ordinal not in range(128)”
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction, IntegrityError

from .models import Album, Artist, Contact, Booking
from .forms import ContactForm
from .forms import ContactForm, ParagraphErrorList


def index(request):
    albums = Album.objects.filter(available=True).order_by('-created_at')[:12]
    context = {
        'albums': albums
    }
    return render(request, 'store/index.html', context)

def listing(request):
    albums_list = Album.objects.filter(available=True)
    paginator = Paginator(albums_list, 9)
    page = request.GET.get('page')
    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        albums = paginator.page(1)
    except EmptyPage:
        albums = paginator.page(paginator.num_pages)
    context = {
        'albums': albums,
        'paginate': True
    }
    return render(request, 'store/listing.html', context)

# methode1: @transaction.atomic ==> les requête s'arrete s'il ya une erreur
def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    artists = [artist.name for artist in album.artists.all()]
    artists_name = " ".join(artists)
    context = {
        'album_title': album.title,
        'artists_name': artists_name,
        'album_id': album.id,
        'thumbnail': album.picture
    }
    if request.method == 'POST':
        form = ContactForm(request.POST, error_class=ParagraphErrorList)
        if form.is_valid():
            email = form.cleaned_data['email']
            name = form.cleaned_data['name']
            
            try:
                with transaction.atomic():
                    contact = Contact.objects.filter(email=email)
                    if not contact.exists():
                        # If a contact is not registered, create a new one.
                        contact = Contact.objects.create(
                            email=email,
                            name=name
                        )
                    else:
                        contact = contact.first()

                    album = get_object_or_404(Album, id=album_id)
                    booking = Booking.objects.create(
                        contact=contact,
                        album=album
                    )
                    album.available = False
                    album.save()
                    context = {
                        'album_title': album.title
                    }
                    return render(request, 'store/merci.html', context)
            except IntegrityError:
                form.errors['internal'] = "Une erreur interne est apparue. Merci de recoommecer votre requête."
       # else:
            # Form data doesn't match the expected format.
            # Add errors to the template.
       #      form = ContactForm()
    else:
        form = ContactForm()
    context['form'] = form
    context['errors'] = form.errors.items()
    return render(request, 'store/detail.html', context)

def search(request):
    query = request.GET.get('query')
    if not query:
        albums = Album.objects.all()
    else:
        # title contains the query is and query is not sensitive to case.
        albums = Album.objects.filter(title__icontains=query)
    if not albums.exists():
        albums = Album.objects.filter(artists__name__icontains=query)
    title = "Résultats pour la requête %s"%query
    context = {
        'albums': albums,
        'title': title
    }
    return render(request, 'store/search.html', context)

disquaire_project/store/templates/store/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

   
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/business-casual.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'store/favicon.ico' %}"/>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">Le bateau pirate</a></div>
    <div class="address-bar">Radio rock, Mer du nord (ou dans le 20e, à Paris)</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Le bateau pirate</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'store:listing' %}">Tous nos disques</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">
      <div class="row">
        <div class="box">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="http://www.hello-birds.com" target="_blank">Céline Martinet Sanchez</a> pour <a href="https://openclassrooms.com" target="_blank">OpenClassrooms</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

  </body>
</html>

disquaire_project/store/templates/store/detail.html
{% extends 'store/base.html' %}

{% block content %}
<hr>
<h1 class="intro-text text-center">{{ album_title }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ thumbnail }}" alt="{{ album_title }}" class="img-responsive">
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px">
    <h2 class="text-center artist_name">Artistes</h2>
    <p>{{ artists_name }}</p>
  </div>

  <h2 class="text-center artist_name">Réserver {{ album_title }}</h2>
  <p style="margin-bottom: 20px;">Demandez-nous de mettre de côté {{ album_title }} et venez le chercher dès demain en magasin ! </p>
  <form class="form-inline" action="{% url 'store:detail' album_id=album_id %}" method="post">
    {% csrf_token %}
    <div class="form-group {% if form.name.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.name.id_for_label }}" class="control-label">Nom</label>
      <!-- <input type="text" name="name" value="" id="name"> -->
      {{ form.name }}
    </div>
    <div class="form-group {% if form.email.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.email.id_for_label }}" class="control-label">E-mail</label>
      <!-- <input type="text" name="email" value="" id="email"> -->
      {{ form.email }}
    </div>
    <!-- <input type="hidden" class="hidden" value="{{ album.id }}" name="album_id"> -->

    <button type="submit" class="btn btn-success">Réserver</button>
  </form>

    {% if errors %}
    <div>
      {% for key, error in errors %}
      {% autoescape off %}
        {{ error }}
      {% endautoescape %}
      {% endfor %}
    </div>
    {% endif %}

</div>


{% endblock %}

disquaire_project/store/templates/store/index.html
{% extends 'store/base.html' %}


{% block content %}

  {% include 'store/list.html' with list_title='Nos derniers disques' %}

{% endblock %}

disquaire_project/store/templates/store/list.html
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}
    </h2>
    <hr class="detail-separator">
</div>

{% include 'store/search_form.html' %}

{% if albums|length_is:"0" %}
    <div class="text-center">
      Palsambleu ! Nous n'avons trouvé aucun résultat à cette requête. Même pas de quoi se ronger la chique !
      Partez de nouveau à l'abordage !
    </div>

{% else %}
    {% for album in albums %}
        <div class="col-sm-4 text-center">
            <a href="{% url 'store:detail' album_id=album.id %}">
              <img class="img-responsive" src="{{ album.picture }}" alt="{{ album.title }}">
            </a>
            <h3><a href="{% url 'store:detail' album_id=album.id %}">{{ album.title }}</a></h3>
            {% for artist in album.artists.all %}
                <p>{{ artist.name }}</p>
            {% endfor %}
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
    {% endfor %}

{% endif %}

{% if paginate %}
  <div class="clearfix"></div>
  <nav aria-label="">
    <ul class="pager">
      {% if albums.has_previous %}
          <li><a href="?page={{ albums.previous_page_number }}">Précédent</a></li>
      {% endif %}
      {% if albums.has_next %}
          <li><a href="?page={{ albums.next_page_number }}">Suivant</a></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

disquaire_project/store/templates/store/listing.html
{% extends 'store/base.html' %}

{% block content %}

    {% include 'store/list.html' with list_title='Tous nos disques' %}

{% endblock %}

disquaire_project/store/templates/store/merci.html
{% extends 'store/base.html' %}

{% block content %}
    <hr>
    <h1 class="intro-text text-center">Merci !</h1>
    <hr class="detail-separator">
    <p>L'album <em>{{ album_title }}</em> vient d'être retiré des rayonnages. Une main délicate a déposé votre nom sur sa couverture et l'a rangé en vous attendant. Dépêchez-vous ! <em>{{ album_title }}</em> trépigne d'impatience et chante déjà vos louanges.</p>
    <hr>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ZSbuikMdgqA" frameborder="0" allowfullscreen></iframe>
    </div>
{% endblock %}

disquaire_project/store/templates/store/search.html
{% extends 'store/base.html' %}

{% block content %}

    {% include 'store/list.html' with list_title=title %}

{% endblock %}

disquaire_project/store/templates/store/search_form.html
<div class="col-lg-12 detail-separator">
  <form class="col-md-6 col-md-offset-3 text-center" action="{% url 'store:search' %}" method="get" accept-charset="utf-8" >
    <div class="form-group">
      <label for="searchForm">Chercher un disque</label>
      <input id="searchForm" class="form-control" name="query">
    </div>
    <span class="help-block" id="helpBlock">Trouvez le CD de vos rêves en tapant son titre ou le nom d'un des artistes.</span>
  </form>
</div>